/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import controller.filmcontroller;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayas
 */
public class crudfilm extends javax.swing.JFrame {

    /**
     * Creates new form crudfilm
     */
    public static int idPegawai;
    filmcontroller f;

    public crudfilm(int idPegawai) {
        initComponents();
        this.idPegawai = idPegawai;

        f = new filmcontroller(this);
        f.isitabel2();

        idKasir.setText(String.valueOf(this.idPegawai));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpegawai = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        pilih = new javax.swing.JButton();
        crudfilm = new javax.swing.JButton();
        datatiket = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        gambar = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tahun1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        durasi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        poster = new javax.swing.JTextField();
        idKasir = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idpegawai.setBackground(new java.awt.Color(30, 24, 24));
        idpegawai.setPreferredSize(new java.awt.Dimension(1512, 982));

        jPanel3.setBackground(new java.awt.Color(86, 9, 9));
        jPanel3.setPreferredSize(new java.awt.Dimension(324, 722));

        logout.setBackground(new java.awt.Color(86, 9, 9));
        logout.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 243, 209));
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 9, 9)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        pilih.setBackground(new java.awt.Color(86, 9, 9));
        pilih.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        pilih.setForeground(new java.awt.Color(255, 243, 209));
        pilih.setText("PILIH FILM");
        pilih.setBorder(null);
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        crudfilm.setBackground(new java.awt.Color(86, 9, 9));
        crudfilm.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        crudfilm.setForeground(new java.awt.Color(231, 170, 0));
        crudfilm.setText("CRUD FILM");
        crudfilm.setBorder(null);
        crudfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudfilmActionPerformed(evt);
            }
        });

        datatiket.setBackground(new java.awt.Color(86, 9, 9));
        datatiket.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        datatiket.setForeground(new java.awt.Color(255, 243, 209));
        datatiket.setText("DATA TIKET");
        datatiket.setBorder(null);
        datatiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datatiketActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icon.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datatiket, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crudfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(pilih)
                .addGap(52, 52, 52)
                .addComponent(datatiket)
                .addGap(70, 70, 70)
                .addComponent(crudfilm)
                .addGap(70, 70, 70)
                .addComponent(logout)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 255, 220));
        jLabel1.setText("MANAGEMENT FILM ");

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelFilm);

        gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)));
        gambar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                gambarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        update.setBackground(new java.awt.Color(8, 86, 59));
        update.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(249, 249, 220));
        update.setText("UBAH");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        id.setEditable(false);
        id.setBackground(new java.awt.Color(30, 24, 24));
        id.setForeground(new java.awt.Color(30, 24, 24));
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        judul.setBackground(new java.awt.Color(37, 42, 45));
        judul.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(248, 255, 228));
        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 254, 245));
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 254, 245));
        jLabel5.setText("Genre");

        genre.setBackground(new java.awt.Color(37, 42, 45));
        genre.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        genre.setForeground(new java.awt.Color(248, 255, 228));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 254, 245));
        jLabel6.setText("Tahun");

        tahun1.setBackground(new java.awt.Color(37, 42, 45));
        tahun1.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        tahun1.setForeground(new java.awt.Color(248, 255, 228));
        tahun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 254, 245));
        jLabel3.setText("Durasi");

        durasi.setBackground(new java.awt.Color(37, 42, 45));
        durasi.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        durasi.setForeground(new java.awt.Color(248, 255, 228));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 254, 245));
        jLabel7.setText("Link Poster");

        poster.setBackground(new java.awt.Color(37, 42, 45));
        poster.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        poster.setForeground(new java.awt.Color(248, 255, 228));

        idKasir.setEditable(false);
        idKasir.setBackground(new java.awt.Color(30, 24, 24));
        idKasir.setForeground(new java.awt.Color(30, 24, 24));
        idKasir.setBorder(null);
        idKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idKasirActionPerformed(evt);
            }
        });

        insert.setBackground(new java.awt.Color(8, 86, 59));
        insert.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        insert.setForeground(new java.awt.Color(249, 249, 220));
        insert.setText("TAMBAH");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(86, 9, 9));
        clear.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(249, 249, 220));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(86, 9, 9));
        delete.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(249, 249, 220));
        delete.setText("HAPUS");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idpegawaiLayout = new javax.swing.GroupLayout(idpegawai);
        idpegawai.setLayout(idpegawaiLayout);
        idpegawaiLayout.setHorizontalGroup(
            idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpegawaiLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idpegawaiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 227, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idpegawaiLayout.createSequentialGroup()
                    .addContainerGap(1431, Short.MAX_VALUE)
                    .addComponent(idKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        idpegawaiLayout.setVerticalGroup(
            idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpegawaiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(insert)
                                .addComponent(update))
                            .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clear)
                                .addComponent(delete))))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(idpegawaiLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(idKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(822, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idpegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 1722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //tombol logout (ke frame login)
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        //cek ulang
        int response = JOptionPane.showConfirmDialog(null,
                "Yakin ingin logout?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            //kode yang dijalankan jika user memilih Yes
            JOptionPane.showMessageDialog(null, "Logout berhasil!");
            login v = new login();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    //tombol ke halaman pilih film
    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        utama v = new utama(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_pilihActionPerformed

    private void crudfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudfilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudfilmActionPerformed

    //tombol ke halaman data tiket
    private void datatiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datatiketActionPerformed
        tampiltiket v = new tampiltiket(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_datatiketActionPerformed

    //jika user meng-klik tabel
    private void tabelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelFilmMouseClicked

        //mengambil data film dari tabel
        int row = tabelFilm.getSelectedRow();
        id.setText(tabelFilm.getValueAt(row, 0).toString());
        judul.setText(tabelFilm.getValueAt(row, 1).toString());
        genre.setText(tabelFilm.getValueAt(row, 2).toString());
        tahun1.setText(tabelFilm.getValueAt(row, 3).toString());
        durasi.setText(tabelFilm.getValueAt(row, 4).toString());
        poster.setText(tabelFilm.getValueAt(row, 5).toString());

        //memunculkan gambar dari url
        String urlGambar = tabelFilm.getValueAt(row, 5).toString();
        try {
            java.net.URL url = new java.net.URL(urlGambar);
            BufferedImage img = ImageIO.read(url);

            if (img != null) {
                //supaya gambar fit di jLabel
                Image scaledImg = img.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(scaledImg);
                gambar.setIcon(imageIcon);
            } else {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat gambar!");
            }
        } catch (MalformedURLException e) {
            System.err.println("Kesalahan pada URL: " + e.getMessage());
        } catch (IOException e) {
            System.err.println("IOException ketika memuat gambar: " + e.getMessage());
        }
    }//GEN-LAST:event_tabelFilmMouseClicked

    //tombol update
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try {
            //jika belum memilih movie
            if (judul.getText().isEmpty() || genre.getText().isEmpty() || tahun1.getText().isEmpty() || durasi.getText().isEmpty() || poster.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih film yang ingin di-update!");
                return;
            }

            f.update();
            f.isitabel2();
            JOptionPane.showMessageDialog(null, "Data film berhasil di-update!");

            //clear text field
            clear();

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_updateActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void idKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idKasirActionPerformed

    //tombol insert
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

        try {

            //jika ada field yang kosong
            if (judul.getText().isEmpty() || genre.getText().isEmpty() || tahun1.getText().isEmpty() || durasi.getText().isEmpty() || poster.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lengkapi data film yang ingin ditambahkan!");
                return;
            }

            //validasi format tahun (YYYY)
            if (!tahun1.getText().matches("\\d{4}")) {
                JOptionPane.showMessageDialog(null, "Format Tahun tidak sesuai! (YYYY)");
                return;
            }

            //validasi format durasi (x jam x menit)
            if (!durasi.getText().matches("\\d+ jam \\d+ menit")) {
                JOptionPane.showMessageDialog(null, "Format Durasi tidak sesuai! (n jam m menit)");
                return;
            }

            //validasi format poster (URL)
            if (!poster.getText().matches("https?://.+")) {
                JOptionPane.showMessageDialog(null, "Format poster harus berupa URL yang valid!");
                return;
            }

            f.insert();
            f.isitabel2();
            JOptionPane.showMessageDialog(null, "Data film berhasil ditambahkan!");

            //clear text field
            clear();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_insertActionPerformed

    //tombol clear
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        try {
            //clear text field
            clear();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_clearActionPerformed

    //tombol hapus
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
            int row = tabelFilm.getSelectedRow();
            //jika belum pilih film
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Pilih film yang ingin dihapus!");
                return;
            }

            String judulP = judul.getText();

            //cek ulang
            int response = JOptionPane.showConfirmDialog(null,
                    "Yakin ingin menghapus film " + judulP + "?",
                    "Konfirmasi Penghapusan",
                    JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                //kode yang dijalankan jika user memilih Yes
                JOptionPane.showMessageDialog(null, "Film berhasil dihapus!");
            } else if (response == JOptionPane.NO_OPTION) {
                //kode yang dijalankan jika user memilih No
                JOptionPane.showMessageDialog(null, "Penghapusan film dibatalkan!");
            }

            f.delete();
            f.isitabel2();
            JOptionPane.showMessageDialog(null, "Data film berhasil dihapus!");

            //clear text field
            clear();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_deleteActionPerformed

    //clear text field
    private void clear() {
        judul.setText("");
        genre.setText("");
        tahun1.setText("");
        durasi.setText("");
        poster.setText("");
        gambar.setIcon(null);
    }

    private void gambarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_gambarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_gambarAncestorAdded

    private void tahun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudfilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudfilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudfilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudfilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudfilm(idPegawai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton crudfilm;
    private javax.swing.JButton datatiket;
    private javax.swing.JButton delete;
    private javax.swing.JTextField durasi;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idKasir;
    private javax.swing.JPanel idpegawai;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul;
    private javax.swing.JButton logout;
    private javax.swing.JButton pilih;
    private javax.swing.JTextField poster;
    private javax.swing.JTable tabelFilm;
    private javax.swing.JTextField tahun1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public static int getIdPegawai() {
        return idPegawai;
    }

    public void setIdPegawai(int idPegawai) {
        this.idPegawai = idPegawai;
    }

    public filmcontroller getF() {
        return f;
    }

    public void setF(filmcontroller f) {
        this.f = f;
    }

    public JButton getCrudfilm() {
        return crudfilm;
    }

    public void setCrudfilm(JButton crudfilm) {
        this.crudfilm = crudfilm;
    }

    public JButton getDatatiket() {
        return datatiket;
    }

    public void setDatatiket(JButton datatiket) {
        this.datatiket = datatiket;
    }

    public JTextField getDurasi() {
        return durasi;
    }

    public void setDurasi(JTextField durasi) {
        this.durasi = durasi;
    }

    public JLabel getGambar() {
        return gambar;
    }

    public void setGambar(JLabel gambar) {
        this.gambar = gambar;
    }

    public JTextField getGenre() {
        return genre;
    }

    public void setGenre(JTextField genre) {
        this.genre = genre;
    }

    public JTextField getId() {
        return id;
    }

    public void setId(JTextField id) {
        this.id = id;
    }

    public JTextField getIdFilm1() {
        return idKasir;
    }

    public void setIdFilm1(JTextField idFilm1) {
        this.idKasir = idFilm1;
    }

    public JPanel getIdpegawai() {
        return idpegawai;
    }

    public void setIdpegawai(JPanel idpegawai) {
        this.idpegawai = idpegawai;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getJudul() {
        return judul;
    }

    public void setJudul(JTextField judul) {
        this.judul = judul;
    }

    public JButton getLogout() {
        return logout;
    }

    public void setLogout(JButton logout) {
        this.logout = logout;
    }

    public JButton getPesan() {
        return update;
    }

    public void setPesan(JButton pesan) {
        this.update = pesan;
    }

    public JButton getPilih() {
        return pilih;
    }

    public void setPilih(JButton pilih) {
        this.pilih = pilih;
    }

    public JTextField getPoster() {
        return poster;
    }

    public void setPoster(JTextField poster) {
        this.poster = poster;
    }

    public JTable getTabelFilm() {
        return tabelFilm;
    }

    public void setTabelFilm(JTable tabelFilm) {
        this.tabelFilm = tabelFilm;
    }

    public JTextField getTahun1() {
        return tahun1;
    }

    public void setTahun1(JTextField tahun1) {
        this.tahun1 = tahun1;
    }

}
