/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import controller.tiketcontroller;
import java.sql.Connection;
import koneksi.connector;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import static project.utama.idPegawai;

/**
 *
 * @author Ayas
 */
public class pesantiket extends javax.swing.JFrame {

    /**
     * Creates new form pesantiket
     */
    Connection connection;
    public static int idPegawai;
    public static int filmId;
    private int idFilm;
    tiketcontroller tc;
    // utama u = new utama(idPegawai);

    public pesantiket(int idPegawai, int filmId) {
        initComponents();

        this.idPegawai = idPegawai;
        this.filmId = filmId;

        tc = new tiketcontroller(this);

        idpegawai.setText(String.valueOf(this.idPegawai));
        pegawai.setText(String.valueOf(this.idPegawai));
        id.setText(String.valueOf(this.filmId));
        connection = connector.connection();
        tc.getDataFilm();
        tc.getNamaPegawai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        poster = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        durasi = new javax.swing.JTextField();
        genre = new javax.swing.JTextField();
        judul4 = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jam = new javax.swing.JTextField();
        jumlahtiket = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        studio = new javax.swing.JTextField();
        kursi = new javax.swing.JTextField();
        metode = new javax.swing.JTextField();
        selesai = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        pegawai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        idpegawai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilih = new javax.swing.JButton();
        datatiket = new javax.swing.JButton();
        crudfilm = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 24, 24));

        jPanel1.setBackground(new java.awt.Color(30, 24, 24));

        poster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 103, 103)));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 254, 245));
        jLabel3.setText("Durasi");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 254, 245));
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 254, 245));
        jLabel5.setText("Genre");

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 254, 245));
        jLabel6.setText("Tahun");

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 254, 245));
        jLabel7.setText("Tanggal");

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 254, 245));
        jLabel8.setText("Jam");

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 254, 245));
        jLabel9.setText("Jumlah Tiket");

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 254, 245));
        jLabel11.setText("Kursi");

        jLabel12.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 254, 245));
        jLabel12.setText("Metode Pembayaran");

        tahun.setEditable(false);
        tahun.setBackground(new java.awt.Color(37, 42, 45));
        tahun.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        tahun.setForeground(new java.awt.Color(248, 255, 228));

        durasi.setEditable(false);
        durasi.setBackground(new java.awt.Color(37, 42, 45));
        durasi.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        durasi.setForeground(new java.awt.Color(248, 255, 228));

        genre.setEditable(false);
        genre.setBackground(new java.awt.Color(37, 42, 45));
        genre.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        genre.setForeground(new java.awt.Color(248, 255, 228));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });

        judul4.setEditable(false);
        judul4.setBackground(new java.awt.Color(37, 42, 45));
        judul4.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        judul4.setForeground(new java.awt.Color(248, 255, 228));
        judul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul4ActionPerformed(evt);
            }
        });

        tanggal.setBackground(new java.awt.Color(37, 42, 45));
        tanggal.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(248, 255, 228));

        jam.setBackground(new java.awt.Color(37, 42, 45));
        jam.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jam.setForeground(new java.awt.Color(248, 255, 228));

        jumlahtiket.setBackground(new java.awt.Color(37, 42, 45));
        jumlahtiket.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jumlahtiket.setForeground(new java.awt.Color(248, 255, 228));

        jLabel14.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 254, 245));
        jLabel14.setText("Studio");

        studio.setBackground(new java.awt.Color(37, 42, 45));
        studio.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        studio.setForeground(new java.awt.Color(248, 255, 228));

        kursi.setBackground(new java.awt.Color(37, 42, 45));
        kursi.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        kursi.setForeground(new java.awt.Color(248, 255, 228));

        metode.setBackground(new java.awt.Color(37, 42, 45));
        metode.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        metode.setForeground(new java.awt.Color(248, 255, 228));

        selesai.setBackground(new java.awt.Color(8, 86, 59));
        selesai.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        selesai.setForeground(new java.awt.Color(186, 171, 171));
        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        batal.setBackground(new java.awt.Color(86, 9, 9));
        batal.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        batal.setForeground(new java.awt.Color(186, 171, 171));
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        id.setEditable(false);
        id.setBackground(new java.awt.Color(30, 24, 24));
        id.setForeground(new java.awt.Color(30, 24, 24));
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        pegawai.setEditable(false);
        pegawai.setBackground(new java.awt.Color(37, 42, 45));
        pegawai.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        pegawai.setForeground(new java.awt.Color(248, 255, 228));
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 254, 245));
        jLabel15.setText("Kasir");

        idpegawai.setEditable(false);
        idpegawai.setBackground(new java.awt.Color(30, 24, 24));
        idpegawai.setForeground(new java.awt.Color(30, 24, 24));
        idpegawai.setBorder(null);
        idpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpegawaiActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(86, 9, 9));
        jPanel3.setPreferredSize(new java.awt.Dimension(324, 722));

        jLabel1.setBackground(new java.awt.Color(253, 255, 245));
        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 255, 228));
        jLabel1.setText("PEMESANAN TIKET");

        pilih.setBackground(new java.awt.Color(86, 9, 9));
        pilih.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        pilih.setForeground(new java.awt.Color(231, 170, 0));
        pilih.setText("PILIH FILM");
        pilih.setBorder(null);
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        datatiket.setBackground(new java.awt.Color(86, 9, 9));
        datatiket.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        datatiket.setForeground(new java.awt.Color(255, 243, 209));
        datatiket.setText("DATA TIKET");
        datatiket.setBorder(null);
        datatiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datatiketActionPerformed(evt);
            }
        });

        crudfilm.setBackground(new java.awt.Color(86, 9, 9));
        crudfilm.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        crudfilm.setForeground(new java.awt.Color(255, 243, 209));
        crudfilm.setText("CRUD FILM");
        crudfilm.setBorder(null);
        crudfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudfilmActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(86, 9, 9));
        logout.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 243, 209));
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 9, 9)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(datatiket, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(crudfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilih)
                            .addComponent(datatiket)
                            .addComponent(crudfilm)
                            .addComponent(logout))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(idpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(300, 300, 300))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(metode, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(62, 62, 62)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(1053, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(metode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batal)
                            .addComponent(selesai)))
                    .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed

        try {
            //mengambil data dari text field
            String judulP = judul4.getText();
            String genreP = genre.getText();
            String tahunP = tahun.getText();
            String durasiP = durasi.getText();
            String tanggalP = tanggal.getText();
            String jamP = jam.getText();
            int jumlahtiketP = Integer.parseInt(jumlahtiket.getText());
            String studioP = studio.getText();
            String kursiP = kursi.getText();
            String metodeP = metode.getText();
            String pegawaiP = pegawai.getText();

            //inisialisasi harga
            int harga = 0;

            //penggolongan harga berdasarkan studio yang dipilih
            if (null != studioP) {
                switch (studioP) {
                    case "2D":
                        harga = 35000;
                        break;
                    case "3D":
                        harga = 50000;
                        break;
                    case "4D":
                        harga = 70000;
                        break;
                    default:
                        break;
                }
            }

            //menghitung bill
            int billP = jumlahtiketP * harga;

            //validasi format tanggal
            if (!isValidDate(tanggalP)) {
                JOptionPane.showMessageDialog(null, "Format tanggal tidak sesuai! (YYYY-MM-DD)");
                return;
            }

            //validasi format jam
            if (!isValidTime(jamP)) {
                JOptionPane.showMessageDialog(null, "Format jam tidak sesuai! (HH:MM)");
                return;
            }

            //validasi format studio
            if (!studioP.matches("2D|3D|4D")) {
                JOptionPane.showMessageDialog(null, "Studio tidak tersedia! \n Studio yang tersedia : 2D, 3D, atau 4D");
                return;
            }

            //validasi format jumlah tiket
            try {
                Integer.parseInt(jumlahtiket.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Jumlah tiket tidak sesuai!");
                return;
            }

            //error handling apabila belum login
            if ("0".equals(idpegawai.getText()) || idpegawai.getText() == null
                    || "".equals(pegawai.getText()) || pegawai.getText() == null) {
                JOptionPane.showMessageDialog(null, "Anda belum login!");
                return;
            }

            //error handling apabila data belum lengkap
            if (tanggalP == null || tanggalP.isEmpty()
                    || jamP == null || jamP.isEmpty()
                    || jumlahtiket.getText() == null || jumlahtiket.getText().isEmpty()
                    || studioP == null || studioP.isEmpty()
                    || kursiP == null || kursiP.isEmpty()
                    || metodeP == null || metodeP.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lengkapi Data Pemesanan!");
                return;
            }

            //insert ke tabel tiket
            tc.insert();

            //pop-up panel tiket
            String ticketMessage = String.format(
                    "====================================================\n"
                    + "                    TIKET BIOSKOP\n"
                    + "====================================================\n"
                    + "Judul       : %s (%s)\n"
                    + "Genre       : %s\n"
                    + "Durasi      : %s\n"
                    + "Tanggal     : %s\n"
                    + "Jam         : %s\n"
                    + "----------------------------------------------------\n"
                    + "Jumlah Tiket: %d\n"
                    + "Studio      : %s\n"
                    + "Kursi       : %s\n"
                    + "Harga/Tiket : Rp %,d\n"
                    + "----------------------------------------------------\n"
                    + "Total       : Rp %,d\n"
                    + "----------------------------------------------------\n"
                    + "Metode Bayar: %s\n"
                    + "Kasir       : %s\n"
                    + "====================================================\n"
                    + "   Terima kasih atas kunjungan Anda!\n"
                    + "====================================================",
                    judulP, tahunP, genreP, durasiP, tanggalP, jamP, jumlahtiketP,
                    studioP, kursiP, harga, billP, metodeP, pegawaiP
            );

            JOptionPane.showMessageDialog(null, ticketMessage);

            //ke frame tampiltiket (tabel data tiket)
            tampiltiket v = new tampiltiket(idPegawai);
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            this.dispose();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_selesaiActionPerformed

    //validasi format tanggal
    private boolean isValidDate(String date) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    //validasi format jam
    private boolean isValidTime(String time) {
        return time.matches("([01]\\d|2[0-3]):([0-5]\\d)");
    }

    //bila klik tombol batal, kembali ke frame utama (memilih film)
    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        //cek ulang
        int response = JOptionPane.showConfirmDialog(null,
                "Yakin ingin membatalkan?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            //kode yang dijalankan jika user memilih Yes
            utama v = new utama(idPegawai); //ke frame utama membawa idPegawai untuk tetap dalam status "login"
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_batalActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void judul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul4ActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pegawaiActionPerformed

    private void idpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpegawaiActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihActionPerformed

    //ke frame data tiket
    private void datatiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datatiketActionPerformed
        tampiltiket v = new tampiltiket(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_datatiketActionPerformed

    //ke frame manajemen film
    private void crudfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudfilmActionPerformed
        crudfilm v = new crudfilm(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_crudfilmActionPerformed

    // logout (ke frame login)
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        //cek ulang
        int response = JOptionPane.showConfirmDialog(null,
                "Yakin ingin logout?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            //kode yang dijalankan jika user memilih Yes
            JOptionPane.showMessageDialog(null, "Logout berhasil!");
            login v = new login();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            this.dispose();
        }

    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesantiket(idPegawai, filmId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton crudfilm;
    private javax.swing.JButton datatiket;
    private javax.swing.JTextField durasi;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idpegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jam;
    private javax.swing.JTextField judul4;
    private javax.swing.JTextField jumlahtiket;
    private javax.swing.JTextField kursi;
    private javax.swing.JButton logout;
    private javax.swing.JTextField metode;
    private javax.swing.JTextField pegawai;
    private javax.swing.JButton pilih;
    private javax.swing.JLabel poster;
    private javax.swing.JButton selesai;
    private javax.swing.JTextField studio;
    private javax.swing.JTextField tahun;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables

    public int getIdPegawai() {
        return idPegawai;
    }

    public void setIdPegawai(int idPegawai) {
        this.idPegawai = idPegawai;
    }

    public JTextField getBill() {
        return metode;
    }

    public void setBill(JTextField Bill) {
        this.metode = Bill;
    }

    public JButton getBatal() {
        return batal;
    }

    public void setBatal(JButton batal) {
        this.batal = batal;
    }

    public JTextField getDurasi() {
        return durasi;
    }

    public void setDurasi(JTextField durasi) {
        this.durasi = durasi;
    }

    public JTextField getGenre() {
        return genre;
    }

    public void setGenre(JTextField genre) {
        this.genre = genre;
    }

    public JTextField getId() {
        return id;
    }

    public void setId(JTextField id) {
        this.id = id;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getPoster() {
        return poster;
    }

    public void setPoster(JLabel poster) {
        this.poster = poster;
    }

    public JTextField getPegawai() {
        return pegawai;
    }

    public void setPegawai(JTextField pegawai) {
        this.pegawai = pegawai;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getJam() {
        return jam;
    }

    public void setJam(JTextField jam) {
        this.jam = jam;
    }

    public JTextField getJudul4() {
        return judul4;
    }

    public void setJudul4(JTextField judul4) {
        this.judul4 = judul4;
    }

    public JTextField getJumlahtiket() {
        return jumlahtiket;
    }

    public void setJumlahtiket(JTextField jumlahtiket) {
        this.jumlahtiket = jumlahtiket;
    }

    public JTextField getKursi() {
        return kursi;
    }

    public void setKursi(JTextField kursi) {
        this.kursi = kursi;
    }

    public JTextField getMetode() {
        return metode;
    }

    public void setMetode(JTextField metode) {
        this.metode = metode;
    }

    public JButton getSelesai() {
        return selesai;
    }

    public void setSelesai(JButton selesai) {
        this.selesai = selesai;
    }

    public JTextField getStudio() {
        return studio;
    }

    public void setStudio(JTextField studio) {
        this.studio = studio;
    }

    public JTextField getTahun() {
        return tahun;
    }

    public JTextField getIdpegawai() {
        return idpegawai;
    }

    public void setIdpegawai(JTextField idpegawai) {
        this.idpegawai = idpegawai;
    }

    public void setTahun(JTextField tahun) {
        this.tahun = tahun;
    }

    public JTextField getTanggal() {
        return tanggal;
    }

    public void setTanggal(JTextField tanggal) {
        this.tanggal = tanggal;
    }

    public static int getFilmId() {
        return filmId;
    }

    public static void setFilmId(int filmId) {
        pesantiket.filmId = filmId;
    }

    public int getIdFilm() {
        return idFilm;
    }

    public void setIdFilm(int idFilm) {
        this.idFilm = idFilm;
    }

}
