/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import controller.filmcontroller;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import javax.imageio.ImageIO;
import java.net.URL.*;
import javax.print.DocFlavor.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static project.pesantiket.idPegawai;

/**
 *
 * @author Ayas
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form tabelFilm
     */
    filmcontroller fc;
    public static int idPegawai;
    public int filmId;

    public utama(int idPegawai) {
        initComponents();

        this.idPegawai = idPegawai;
        fc = new filmcontroller(this);
        fc.isitabel();

        idFilm.setText("0");
        id.setText(String.valueOf(this.idPegawai));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpegawai = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        pilih = new javax.swing.JButton();
        crudfilm = new javax.swing.JButton();
        datatiket = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        gambar = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        durasi = new javax.swing.JTextField();
        tahun1 = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();
        idFilm = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idpegawai.setBackground(new java.awt.Color(30, 24, 24));
        idpegawai.setPreferredSize(new java.awt.Dimension(1512, 982));

        jPanel3.setBackground(new java.awt.Color(86, 9, 9));

        logout.setBackground(new java.awt.Color(86, 9, 9));
        logout.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 243, 209));
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 9, 9)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        pilih.setBackground(new java.awt.Color(86, 9, 9));
        pilih.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        pilih.setForeground(new java.awt.Color(231, 170, 0));
        pilih.setText("PILIH FILM");
        pilih.setBorder(null);
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        crudfilm.setBackground(new java.awt.Color(86, 9, 9));
        crudfilm.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        crudfilm.setForeground(new java.awt.Color(255, 243, 209));
        crudfilm.setText("CRUD FILM");
        crudfilm.setBorder(null);
        crudfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudfilmActionPerformed(evt);
            }
        });

        datatiket.setBackground(new java.awt.Color(86, 9, 9));
        datatiket.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        datatiket.setForeground(new java.awt.Color(255, 243, 209));
        datatiket.setText("DATA TIKET");
        datatiket.setBorder(null);
        datatiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datatiketActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icon.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datatiket, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(pilih)
                .addGap(70, 70, 70)
                .addComponent(datatiket)
                .addGap(70, 70, 70)
                .addComponent(crudfilm)
                .addGap(70, 70, 70)
                .addComponent(logout)
                .addGap(92, 92, 92))
        );

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 255, 220));
        jLabel1.setText("PILIH FILM ANDA <3");

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelFilm);

        gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)));

        genre.setEditable(false);
        genre.setBackground(new java.awt.Color(30, 24, 24));
        genre.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        genre.setForeground(new java.awt.Color(253, 255, 234));
        genre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        genre.setText("Genre");
        genre.setBorder(null);
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });

        durasi.setEditable(false);
        durasi.setBackground(new java.awt.Color(30, 24, 24));
        durasi.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        durasi.setForeground(new java.awt.Color(253, 255, 234));
        durasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        durasi.setText("Durasi");
        durasi.setBorder(null);
        durasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasiActionPerformed(evt);
            }
        });

        tahun1.setEditable(false);
        tahun1.setBackground(new java.awt.Color(30, 24, 24));
        tahun1.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        tahun1.setForeground(new java.awt.Color(253, 255, 234));
        tahun1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tahun1.setText("Tahun");
        tahun1.setBorder(null);
        tahun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun1ActionPerformed(evt);
            }
        });

        pesan.setBackground(new java.awt.Color(86, 9, 9));
        pesan.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        pesan.setForeground(new java.awt.Color(249, 249, 220));
        pesan.setText("PESAN");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        idFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFilmActionPerformed(evt);
            }
        });

        judul.setEditable(false);
        judul.setBackground(new java.awt.Color(30, 24, 24));
        judul.setFont(new java.awt.Font("Sitka Display", 1, 28)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 197, 47));
        judul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        judul.setText("Judul");
        judul.setBorder(null);
        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idpegawaiLayout = new javax.swing.GroupLayout(idpegawai);
        idpegawai.setLayout(idpegawaiLayout);
        idpegawaiLayout.setHorizontalGroup(
            idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpegawaiLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(321, 321, 321)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(120, Short.MAX_VALUE))))
        );
        idpegawaiLayout.setVerticalGroup(
            idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idpegawaiLayout.createSequentialGroup()
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(idpegawaiLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(idpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(pesan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idpegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 1897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 408, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void durasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durasiActionPerformed

    private void tahun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun1ActionPerformed

    //jika user meng-klik tabel film
    private void tabelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelFilmMouseClicked

        //mengambil data dari baris yang dipilih
        int row = tabelFilm.getSelectedRow();
        idFilm.setText(tabelFilm.getValueAt(row, 0).toString());
        judul.setText(tabelFilm.getValueAt(row, 1).toString());
        genre.setText(tabelFilm.getValueAt(row, 2).toString());
        tahun1.setText(tabelFilm.getValueAt(row, 3).toString());
        durasi.setText(tabelFilm.getValueAt(row, 4).toString());
        
        //memunculkan gambar dari url
        String urlGambar = tabelFilm.getValueAt(row, 5).toString();
        try {
            java.net.URL url = new java.net.URL(urlGambar);
            BufferedImage img = ImageIO.read(url);

            if (img != null) {
                //supaya gambar fit di jLabel
                Image scaledImg = img.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(scaledImg);
                gambar.setIcon(imageIcon);
            } else {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat gambar!");
            }
        } catch (MalformedURLException e) {
            System.err.println("Kesalahan pada URL: " + e.getMessage());
        } catch (IOException e) {
            System.err.println("IOException ketika memuat gambar: " + e.getMessage());
        }
    }//GEN-LAST:event_tabelFilmMouseClicked

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    //tombol pesan
    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        
        //error handling apabila belum login
        if ("0".equals(id.getText()) || id.getText() == null) {
            JOptionPane.showMessageDialog(null, "Anda Belum Login");
            return;
        }
        
        //error handlling jika belum memilih film
        if ("0".equals(idFilm.getText()) || idFilm.getText() == null
                || "Judul".equals(judul.getText())
                || "Genre".equals(genre.getText())
                || "Tahun".equals(tahun1.getText())
                || "Durasi".equals(durasi.getText())) {
            JOptionPane.showMessageDialog(null, "Film Belum DIpilih");
            return;
        }

        filmId = Integer.parseInt(getIdFilm().getText());
        
        //ke frame pesantiket
        pesantiket v = new pesantiket(idPegawai, filmId);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_pesanActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
    }//GEN-LAST:event_idActionPerformed

    private void idFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilmActionPerformed
    }//GEN-LAST:event_idFilmActionPerformed

    //tombol logout
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        //cek ulang
        int response = JOptionPane.showConfirmDialog(null,
                "Yakin ingin logout?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            //kode yang dijalankan jika user memilih Yes
            JOptionPane.showMessageDialog(null, "Logout berhasil!");
            login v = new login();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
    }//GEN-LAST:event_pilihActionPerformed

    //tombol ke manajemen film
    private void crudfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudfilmActionPerformed
        crudfilm v = new crudfilm(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_crudfilmActionPerformed

    //tombol ke tabel tiket (melihat data tiket)
    private void datatiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datatiketActionPerformed
        tampiltiket v = new tampiltiket(idPegawai);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_datatiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabelFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabelFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabelFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabelFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new utama(idPegawai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crudfilm;
    private javax.swing.JButton datatiket;
    private javax.swing.JTextField durasi;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idFilm;
    private javax.swing.JPanel idpegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul;
    private javax.swing.JButton logout;
    private javax.swing.JButton pesan;
    private javax.swing.JButton pilih;
    private javax.swing.JTable tabelFilm;
    private javax.swing.JTextField tahun1;
    // End of variables declaration//GEN-END:variables

    public JTextField getDurasi() {
        return durasi;
    }

    public void setDurasi(JTextField durasi) {
        this.durasi = durasi;
    }

    public JTextField getGenre() {
        return genre;
    }

    public void setGenre(JTextField genre) {
        this.genre = genre;
    }

    public JButton getjButton1() {
        return pesan;
    }

    public void setjButton1(JButton jButton1) {
        this.pesan = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return gambar;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.gambar = jLabel2;
    }

    public JPanel getjPanel1() {
        return idpegawai;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.idpegawai = jPanel1;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getJudul() {
        return judul;
    }

    public void setJudul(JTextField judul) {
        this.judul = judul;
    }

    public JTable getTabelFilm() {
        return tabelFilm;
    }

    public void setTabelFilm(JTable tabelFilm) {
        this.tabelFilm = tabelFilm;
    }

    public JTextField getTahun1() {
        return tahun1;
    }

    public void setTahun1(JTextField tahun1) {
        this.tahun1 = tahun1;
    }

    public filmcontroller getFc() {
        return fc;
    }

    public void setFc(filmcontroller fc) {
        this.fc = fc;
    }

    public JTextField getIdFilm() {
        return idFilm;
    }

    public void setIdFilm(JTextField idFilm) {
        this.idFilm = idFilm;
    }

    public JButton getPesan() {
        return pesan;
    }

    public void setPesan(JButton pesan) {
        this.pesan = pesan;
    }

    public JLabel getGambar() {
        return gambar;
    }

    public static int getIdPegawai() {
        return idPegawai;
    }

    public static void setIdPegawai(int idPegawai) {
        utama.idPegawai = idPegawai;
    }

    public JTextField getId() {
        return id;
    }

    public void setId(JTextField id) {
        this.id = id;
    }

    private static class tabelFilm {

        public tabelFilm() {
        }
    }

}
